### ISSUE TITLE
Explore Binance API

### ISSUE THREAD

**Issue by vyakov** [kalinpetrovbg/My-Wallet-Project#10]

**Comment by KoliosterNikolayIliev** [comment]
Write simple script covering API functionalities(requests, responses) .

**Comment by KoliosterNikolayIliev** [comment]
Current progress - https://docs.google.com/document/d/1mXj77p5LzQElS8LnxUlHTmAa2xpj5ocCGfOnqlFqyKw/edit#

**Comment by KoliosterNikolayIliev** [comment]
[https://docs.google.com/document/d/1mXj77p5LzQElS8LnxUlHTmAa2xpj5ocCGfOnqlFqyKw/edit#heading=h.whnga31vddvy](url)
