### ISSUE TITLE
Exercise Nordigen Sandbox capabilities

### ISSUE THREAD

**Issue by smanilov** [kalinpetrovbg/My-Wallet-Project#19]
https://nordigen.com/en/account_information_documenation/integration/sandbox/

Follow-up of issue #8

**Comment by smanilov** [comment]
#8

**Comment by Sheko1** [comment]
First we need a [requisition_id](https://github.com/kalinpetrovbg/My-Wallet-Project/tree/main/api-demos/nordigen-api-demo#step-4---create-a-requisition) and then we can [build a ASPSP link](https://github.com/kalinpetrovbg/My-Wallet-Project/tree/main/api-demos/nordigen-api-demo#step-5---build-a-link) with **SANDBOXFINANCE_SFIN0000** as **aspsp_id**.
Then it doesn't matter what user id and code you enter to sign in. After that you can see [linked accounts](https://github.com/kalinpetrovbg/My-Wallet-Project/tree/main/api-demos/nordigen-api-demo#step-6---list-accounts) and use these [methods](https://github.com/kalinpetrovbg/My-Wallet-Project/tree/main/api-demos/nordigen-api-demo#function-you-can-use-after-you-linked-bank-account) to receive data.
