### ISSUE TITLE
Investigate how suitable is Django for a microservices-based project

### ISSUE THREAD

**Issue by smanilov** [kalinpetrovbg/My-Wallet-Project#42]
https://www.pluralsight.com/guides/develop-a-microservice-api-with-django-rest-framework-(drf)

**Comment by DimoDimchev** [comment]
Take a look at [this](https://github.com/michaellitherland/flask-microservice-demo) Flask microservices demo and [this](https://github.com/cyantarek/django-microservices) Django microservices demo.

I think we should combine both frameworks and do some of the microservices in Django(the ones that require harder logic) and the rest in Flask(the ones that are simpler)
