### ISSUE TITLE
Research and planning on 'Reference' Flask microservice

### ISSUE THREAD

**Issue by DimoDimchev** [kalinpetrovbg/My-Wallet-Project#46]
This issue should:
- Decide what source to use for reference data(Yahoo Reference, Polygon, etc.)
- Choose and describe all endpoints the API will have
- Create a graph for the microservice

**Comment by DimoDimchev** [comment]
Discussion here or [here](https://docs.google.com/document/d/1CibeTb5xOnKsXpps_zHxHH6s67x6QfMsmyK4A2eWyyU/edit?usp=sharing)

**Comment by DimoDimchev** [comment]
## Status update
Currently facing a dead end. It appears most third-party APIs for accessing stocks and crypto price data offer a free tier for personal use only. Furthermore, these free tiers limit the number of requests we can use per month(e.g 250/500) which isn't at all sufficient for a big application like ours. 

## Why isn't it suffficient?
That is because using these APIs we can't get data for multiple stocks at once. This means that we need to send a unique set of requests for every user and the stocks they own(one request per each stock). If we have a user-base of 500 the 500 requests/month limit would be reached in less than a single day.

## Possible solutions
Currently, I have no suggestions as to how to solve this problem. Any suggestions would be appreciated

**Comment by DimoDimchev** [comment]
## Status update
After today's daily meeting and a brief discussion with one of the product owners we decided to proceed as follows:
- ### For stocks:
    * For the purpose of creating an MVP we will settle for a free tier from one of the API's - [twelvedata](https://twelvedata.com/) and their Python library
    * We will keep track of all stocks on the platform(starting with 10 base ones and going from there) and receive update data for them only
    * Update reference prices once every day

- ### For crypto:
    * For the purpose of creating an MVP we will explore [Coinlayer](https://coinlayer.com/) and Binance's API and select the better option
    * Use the same overall strategy as stocks with the only difference that we'll try to update the prices as often as possible since cryptocurrencies are volatile assets

**Comment by dikors** [comment]
> ## Status update
> After today's daily meeting and a brief discussion with one of the product owners we decided to proceed as follows:
> 
> * ### For stocks:
>   
>   * For the purpose of creating an MVP we will settle for a free tier from one of the API's - [twelvedata](https://twelvedata.com/) and their Python library
>   * We will keep track of all stocks on the platform(starting with 10 base ones and going from there) and receive update data for them only
>   * Update reference prices once every day
> * ### For crypto:
>   
>   * For the purpose of creating an MVP we will explore [Coinlayer](https://coinlayer.com/) and Binance's API and select the better option
>   * Use the same overall strategy as stocks with the only difference that we'll try to update the prices as often as possible since cryptocurrencies are volatile assets



> ## Status update
> After today's daily meeting and a brief discussion with one of the product owners we decided to proceed as follows:
> 
> * ### For stocks:
>   
>   * For the purpose of creating an MVP we will settle for a free tier from one of the API's - [twelvedata](https://twelvedata.com/) and their Python library
>   * We will keep track of all stocks on the platform(starting with 10 base ones and going from there) and receive update data for them only
>   * Update reference prices once every day
> * ### For crypto:
>   
>   * For the purpose of creating an MVP we will explore [Coinlayer](https://coinlayer.com/) and Binance's API and select the better option
>   * Use the same overall strategy as stocks with the only difference that we'll try to update the prices as often as possible since cryptocurrencies are volatile assets

Here are 10 stock tickers we can use for our tests:
AMZN
MSFT
GOOGL
AMD
MRNA
TSLA
PLTR
AAPL
LCID
GME
