### ISSUE TITLE
Start implementing Account microservice

### ISSUE THREAD

**Issue by smanilov** [kalinpetrovbg/My-Wallet-Project#54]

**Comment by KoliosterNikolayIliev** [comment]
- Use already created server and rename it.
- Install dependencies
- Create structure

**Comment by KoliosterNikolayIliev** [comment]
in progress branch [here](https://github.com/kalinpetrovbg/My-Wallet-Project/tree/origin/niki%2Fissue%2F54%2Fmicroservices%2Faccount)
