### ISSUE TITLE
Explore Interactive Brokers API

### ISSUE THREAD

**Issue by smanilov** [kalinpetrovbg/My-Wallet-Project#7]
Might require the creation of a demo account for the purpose of integration.

Create simple script / CLI app to demonstrate connection.

**Comment by DimoDimchev** [comment]
Concluded research on the Interactive Brokers API [here](https://docs.google.com/document/d/1npOYEGADGFmFffhaeixC7SVntNQBk8l16MqYto61FRw/edit?usp=sharing). 

After a bad experience with other online brokers decided to discuss a move to data aggregators [here](https://docs.google.com/document/d/1wvrmNVIOKKcrgtTdvTccNtPAPhEnfxfCWvJaeUGUjzk/edit?usp=sharing)
